legacy/pages/adherents-creer.php
legacy/scripts/operations/operations.user_create.php

si on ne remplit pas certains champs pourtant non indiqués comme obligatoires

fix: erreurs à la création d'un utilisateur

---

legacy/app/fonctions.php
legacy/includes/evt/feuille_de_sortie.php

https://app.clickup.com/t/86c4ajgjj
AVANT
APRÈS

feat: prénom puis nom sur fiche sortie

---

src/Controller/SortieController.php
src/Entity/User.php
src/Repository/EventParticipationRepository.php
src/Utils/ExcelExport.php
tests/Utils/ExcelExportTest.php

https://app.clickup.com/t/86c34a1cy
https://app.clickup.com/t/86c2rrn58
https://app.clickup.com/t/86c4a3pvh
AVANT
[tes1749544348.xlsx](https://github.com/user-attachments/files/20668484/tes1749544348.xlsx)
APRÈS
[test-lieu-de-rdv.2025-06-10.10-56-38.xlsx](https://github.com/user-attachments/files/20669200/test-lieu-de-rdv.2025-06-10.10-56-38.xlsx)

feat: fiche sortie Excel

---

assets/commission-switch.js
src/Controller/CommissionController.php
src/Form/EventType.php
templates/form/field_group.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c3fx3uf
AVANT
APRÈS

feat: retirer la notion de groupe dans les sorties

---

legacy/pages/gestion-des-articles.php
src/Repository/ArticleRepository.php

sont soumis à la validation au sein de la commission de la sortie liée
https://app.clickup.com/t/86c3zfrb8
remplace https://github.com/Club-Alpin-Lyon-Villeurbanne/plateforme-club-alpin/pull/1148

feat: validation des articles CR de sortie

---

src/Controller/SortieController.php

https://app.clickup.com/t/860paa6tf
APRÈS

feat: prévenir tous les encadrants des désinscriptions

---

assets/styles/styles.css
legacy/includes/agenda-evt-courant.php
legacy/includes/agenda-evt-debut.php
legacy/includes/evt-temoin-reqs.php
legacy/pages/agenda.php
legacy/pages/gestion-des-sorties.php
legacy/pages/recherche.php
legacy/scripts/fonctions.php
migrations/Version20250513115648.php
src/Bridge/Twig/TwigExtension.php
src/Controller/ArticleController.php
src/Controller/SortieController.php
src/Entity/Evt.php
src/Form/ArticleType.php
src/Form/EventType.php
src/Repository/EvtRepository.php
templates/article/edit.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c3ah3nq
APRÈS
et sur le dépôt d'article, on uniformise :

feat: sortie en brouillon

---

assets/styles/styles.css
templates/components/cancel-participation.html.twig

https://app.clickup.com/t/86c11c1jg
AVANT
APRÈS

fix: taille des boutons

---

assets/styles/styles.css
templates/header.html.twig

fix: menu alignement des puces

---

legacy/pages/annuler-une-sortie.php
legacy/scripts/operations/operations.evt_cancel.php
migrations/Version20250710130916.php
src/Entity/EventParticipation.php
src/Security/Voter/SortieAnnulationVoter.php

https://app.clickup.com/t/86c4cz0ut

feat: droits d'annulation de sortie

---

migrations/Version20250618133030.php
src/Controller/ArticleController.php
src/Entity/Article.php
templates/article/article.html.twig

https://github.com/Club-Alpin-Lyon-Villeurbanne/caflyon/pull/1080/files
modifs perdues suite rebase ><

feat: page article - dernière modif

---

assets/ckeditor.js
assets/styles/common.css
composer.json
composer.lock
config/bundles.php
legacy/editElt.php
package-lock.json
package.json
src/Form/ArticleType.php
src/Form/EventType.php
symfony.lock
templates/article/edit.html.twig
templates/sortie/formulaire.html.twig
vite.config.js

https://app.clickup.com/t/86c3mhyxk
AVANT
APRÈS

feat: nouvel éditeur wysiwyg

---

src/Controller/SortieController.php
src/Form/EventType.php

https://app.clickup.com/t/86c4kpkvp

fix: prix peut être nul

---

templates/macros/cancel_block.html.twig
templates/sortie/sortie.html.twig

encore du code qui avait sauté à un merge ou rebase
fonctionnalité déjà en prod

feat: factoriser code

---

legacy/pages/user-full.php

https://app.clickup.com/t/86c3kkrr4

feat: message d'erreur si non connecté

---

src/Form/EventType.php
templates/sortie/sortie.html.twig

et afficher l'heure de retour
https://app.clickup.com/t/86c45pymm, https://app.clickup.com/t/86c4krn59 et https://app.clickup.com/t/86c4hk5qb
AVANT
APRÈS

feat: rendre obligatoires 3 champs de plus

---

assets/styles/styles.css
src/Controller/SortieController.php
templates/sortie/sortie.html.twig
tests/Controller/SortieControllerTest.php

https://app.clickup.com/t/86byc81bv
AVANT
APRÈS

feat: sélectionner les gens à contacter

---

composer.json
composer.lock
migrations/Version20250723071647.php
migrations/Version20250723073439.php
src/Entity/Competence.php
src/Entity/FormationValidee.php
src/Entity/LastSync.php
src/Entity/NiveauPratique.php
src/Repository/CompetenceRepository.php
src/Repository/FormationValideeRepository.php
src/Repository/LastSyncRepository.php
src/Repository/NiveauPratiqueRepository.php

https://app.clickup.com/t/86c4b2xze => création des tables nécessaires via migration
@NicolasRitouet tu peux merger dès que c'est bon pour toi

feat: créer les tables pour les brevets et compétences FFCAM

---

src/Entity/Article.php
src/Entity/User.php
symfony.lock

retirer code obsolète et resynchro le code avec les migrations

fix: nettoyer code

---

assets/styles/common.css
src/Controller/SortieController.php
src/Form/EventType.php
templates/macros/form_macros.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c10bj44
AVANT
APRÈS

feat: dépublier sortie si certains champs sont modifiés

---

legacy/scripts/operations/operations.user_join_manuel.php
templates/email/transactional/sortie-inscription-manuelle.html.twig

https://app.clickup.com/t/86byc6nvf
APRÈS

feat: notifier les encadrants d'un ajout manuel

---

templates/sortie/sortie.html.twig

https://app.clickup.com/t/86byc81bv

fix: destinataires possibles

---

src/Controller/SortieController.php
src/Form/EventType.php
templates/macros/form_macros.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c4kryep, https://app.clickup.com/t/86c4pab4y et https://app.clickup.com/t/86c4par3p

fix: champs obligatoires, revalidation nécessaire

---

templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c4rr9j1
AVANT
APRÈS

fix: améliorations envoi groupé à destinataires sélectionnés

---

legacy/pages/accueil.php
templates/email/transactional/sortie-modifiee.html.twig

https://app.clickup.com/t/86c4tfecu
AVANT
APRÈS

fix: filtre trop restrictif sur liste articles

---

legacy/pages/recherche.php

https://app.clickup.com/t/86c4tv6a4

fix: erreurs dans la recherche

---

src/Controller/SortieController.php
templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c40bc64

feat: ne plus permettre de ne pas envoyer les emails

---

src/Controller/ArticleController.php
src/Controller/CommissionController.php
src/Form/ArticleType.php
src/Helper/MonthHelper.php
src/Repository/EvtRepository.php
templates/article/edit.html.twig
templates/form/field_events.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c3fjhma
AVANT
APRÈS

feat: inciter à rédiger des CRs

---

legacy/scripts/operations/operations.user_join.php

https://app.clickup.com/t/86c46ew39

fix: participant sans rôle

---

src/Controller/CommissionController.php
src/Form/ArticleType.php

https://app.clickup.com/t/86c4zrb4m
AVANT
APRÈS

fix: sorties des commissions sur lesquelles on est rédacteur

---

src/Controller/ArticleController.php

https://app.clickup.com/t/86c574294

fix: lien dans l'email de commentaire article

---

legacy/includes/user/display_status.php
legacy/includes/user/statuts.php
legacy/pages/profil-infos.php
src/Entity/UserAttr.php

https://app.clickup.com/t/86c53aunv
AVANT
APRÈS

feat: infobulle description du rôle

---

src/Controller/SortieController.php

https://app.clickup.com/t/86c56mw32

feat: envoyer directement le mail de modif de sortie

---

legacy/scripts/operations/operations.user_join_manuel.php
src/Controller/SortieController.php

https://app.clickup.com/t/86c2fvq06
APRÈS

feat: empêcher le surbooking

---

config/services.yaml
legacy/pages/adherents-droits.php
legacy/pages/adherents.php
legacy/pages/admin-users-droits.php
legacy/scripts/operations.php
legacy/scripts/operations/operations.user_attr_add.php
legacy/scripts/operations/operations.user_attr_add_admin.php
src/Service/UserRightService.php
templates/email/transactional/droits/ajout-utilisateur.html.twig
templates/email/transactional/droits/suppression-utilisateur.html.twig

https://app.clickup.com/t/86c3fddth

feat: notifier l'adhérent quand ses statuts changent

---

legacy/scripts/operations/operations.user_join_manuel.php
src/Controller/SortieController.php

https://app.clickup.com/t/86c2fvq06

feat: wording surbooking

---

legacy/app/fonctions.php
legacy/includes/join_manual.php
legacy/pages/adherents.php
legacy/pages/admin-users.php
legacy/pages/annuler-une-sortie.php

https://app.clickup.com/t/86c50v4xr
AVANT
APRÈS

fix: caractères accentués dans les noms de famille en majuscules

---

assets/styles/styles.css

https://app.clickup.com/t/86c4u53cm
AVANT
APRÈS

fix: affichage des puces dans les pages libres

---

templates/content_html/alerte-licence-renouveler.html.twig

Met à jour le lien de renouvellement de la licence dans le contenu d’alerte.\n\n- Fichier: \n- Lien cible: https://extranet-clubalpin.com/monespace/\n\nVérification\n- Ouvrir l’alerte côté back-office / rendu HTML et cliquer sur le lien.\n- Confirmer la redirection vers l’extranet (Mon espace).

chore(content): mise à jour du lien de renouvellement de la licence

---

templates/profil/sorties.html.twig

https://app.clickup.com/t/86c4mmzxm
AVANT
APRÈS

fix: liste sorties : prio statuts

---

legacy/pages/adherents-droits.php
legacy/pages/admin-users-droits.php
src/Service/UserRightService.php

https://app.clickup.com/t/86c5buqq5

feat: ne pas notifier les VP des changements de responsabilités

---

templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c4thm66
AVANT
APRÈS

feat: dépôt sortie : style bouton

---

assets/styles/styles.css
migrations/Version20250828140627.php
src/Controller/UserController.php
src/Repository/UserAttrRepository.php
templates/base-wide.html.twig
templates/header.html.twig
templates/user/status-list.html.twig

https://app.clickup.com/t/86c3bpej7

feat: liste globale des statuts des adhérents

---

migrations/Version20250908132603.php
templates/local_club/index.html.twig
templates/minibus/index.html.twig

https://app.clickup.com/t/86c4gntq2
même principe que dans https://github.com/Club-Alpin-Lyon-Villeurbanne/plateforme-club-alpin/pull/1242

feat: rendre administrables certains contenus de pages fixes

---

assets/styles/styles.css
config/services.yaml
migrations/Version20250909122642.php
src/Controller/SortieController.php
src/Entity/Evt.php
src/Form/ArticleType.php
src/Form/EventType.php
templates/article/edit.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c4ynx47
AVANT
APRÈS

feat: disclaimer images sur dépôt sortie

---

src/Controller/ArticleController.php
src/Controller/SortieController.php
src/Controller/UserController.php
src/EventListener/Entity/ExpenseReportStatusChangeSubscriber.php
src/Service/UserRightService.php

https://app.clickup.com/t/86c5baug7
je n'ai pas ajouté de try/catch autour de certains envois de mails que j'ai jugés absolument nécessaires (ex lien de reset du mot de passe)
si l'envoi plante, il ne faut pas que l'utilisateur puisse penser que tout va bien ^^

fix: empêcher qu'un échec d'envoi de mail arrête le traitement

---

legacy/pages/accueil.php
templates/email/transactional/notification-new-article.html.twig
templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c5eyu3g

fix: liens vers article pour éviter les erreurs d'inclusion legacy

---

src/Repository/UserRepository.php

https://app.clickup.com/t/86c5j71em

fix: ignorer la casse dans la détection de doublon (import FFCAM)

---

legacy/includes/fiche-profil.php
legacy/pages/responsables.php
legacy/pages/user-full.php
src/Controller/UserController.php
src/Entity/User.php
src/Repository/UserAttrRepository.php
src/Repository/UserRepository.php
templates/sortie/sortie.html.twig

et ne pas permettre de les trouver dans les listes
https://app.clickup.com/t/86c5m3d5j
si jamais un utilisateur qui était inscrit à une sortie est supprimé, voici le rendu

fix: ne pas afficher les utilisateurs "supprimés"

---

templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c5m36bq

fix: saut de ligne

---

legacy/pages/accueil.php
public/js/accueil.js

https://app.clickup.com/t/86c5mjk1e

fix: slider page d'accueil

---

templates/sortie/feuille-sortie.html.twig

https://app.clickup.com/t/86c5npgmt

fix: alignement fiche de sortie

---

legacy/app/fonctions.php
legacy/includes/user/display_name.php
legacy/pages/adherents-consulter.php
legacy/pages/adherents-creer.php
legacy/pages/adherents-modifier.php
legacy/pages/adherents.php
legacy/pages/admin-users.php
legacy/pages/profil-infos.php
legacy/scripts/operations/operations.user_contact.php
legacy/scripts/operations/operations.user_create.php
src/Controller/UserController.php
templates/user/manual-add-select.html.twig

https://app.clickup.com/t/86c5fuqzn et https://app.clickup.com/t/86c433jqu

feat: retirer la civilité (affichage)

---

assets/styles/styles.css
src/Controller/UserController.php
templates/user/nomad-add.html.twig

https://app.clickup.com/t/86c5npvhv

fix: vérification contraintes d'unicité

---

docs/api.md
src/Bridge/Twig/TwigExtension.php
templates/sortie/sortie.html.twig
templates/user/manual-add.html.twig
translations/messages.fr.yaml

https://app.clickup.com/t/86c0fcztf

feat: changement de libellé

---

config/services.yaml
src/Controller/EventManagementController.php
src/Notifications.php

https://app.clickup.com/t/86c5qammt

fix: bulles-compteur de notifications dans le menu

---

src/Utils/ExcelExport.php
templates/sortie/feuille-sortie.html.twig

https://app.clickup.com/t/86c5fuqzn

fix: retrait civilité

---

migrations/Version20250930071903.php
src/Entity/User.php
src/EventListener/LoginSuccessListener.php

https://app.clickup.com/t/86c5jw996

feat: enregistrer la date de dernière connexion

---

src/Controller/SortieController.php
templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c4hnd3x
et empêcher les encadrants et initiateurs stagiaires de se désinscrire tous seuls simplement

feat: ne pas pouvoir désinscrire facilement un initiateur stagiaire

---

assets/commission-switch.js
migrations/Version20250911142044.php
migrations/Version20250911153121.php
migrations/Version20250926085344.php
src/Controller/CommissionController.php
src/Controller/SortieController.php
src/Entity/Commission.php
src/Form/EventType.php
src/Helper/EventFormHelper.php
src/Security/Voter/CommissionConfigVoter.php
templates/commission/configuration.html.twig
templates/commission/index.html.twig
templates/form/commission_specific_fields.html.twig
templates/header.html.twig
templates/sortie/formulaire.html.twig

https://app.clickup.com/t/86c595kr0

feat: paramétrer champs obligatoires par commission

---

src/Controller/SortieController.php
src/Entity/Evt.php
src/Form/EventType.php
templates/email/transactional/sortie-demande-inscription-confirmation.html.twig
templates/email/transactional/sortie-demande-inscription.html.twig
templates/email/transactional/sortie-inscription-manuelle.html.twig
templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c5jfz0k et https://app.clickup.com/t/86c5nzzwg

feat: liste d'attente simple

---

src/Controller/SortieController.php
src/Entity/Evt.php
src/Form/EventType.php
templates/email/transactional/sortie-demande-inscription-confirmation.html.twig
templates/sortie/sortie.html.twig

https://app.clickup.com/t/86c5jfz0k
reverts https://github.com/Club-Alpin-Lyon-Villeurbanne/plateforme-club-alpin/pull/1337

fix: revert file d'attente

---

legacy/scripts/operations/operations.user_update.php

https://app.clickup.com/t/86c5vt5tz

hotfix: mise à jour de mon compte
